apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab9z2-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: lab9z2
  template:
    metadata:
      labels:
        app: lab9z2
    spec:
      containers:
      - name: lab9z2
        image: olszewskista/lab9z2:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab9z2-service
spec:
  type: NodePort
  selector:
    app: lab9z2
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
