version: '3.8'
services:
  db:
    image: mongo:${MONGO_VERSION}
    networks:
      - net_A
    volumes:
      - ../zad1/data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    container_name: db
  server:
    build: ./app
    networks:
      - net_A
    depends_on:
      - db
    ports:
      - "3003:3000"
    container_name: server

networks:
  net_A: