version: '3.9'
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - frontend_network
  backend:
    build: ./backend
    depends_on:
      - db
    networks:
      - backend_network
      - frontend_network
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - frontend_network
  db:
    image: mongo
    networks:
      - backend_network

networks:
  frontend_network:
  backend_network: