apiVersion: v1
kind: Pod
metadata:
  name: lab9z1-pod
spec:
  containers:
  - name: lab9z1-con
    image: olszewskista/lab9z1:2.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
